### ISSUE TITLE
instanceOfEcdsaSignature in SignerAlgorithm be of type any? [WARNING]

### ISSUE THREAD

**Issue by bshambaugh** [decentralized-identity/did-jwt#214] opened 2022-01-18 18:02 UTC
# Current Behavior

I get this linter warning. I am not sure whether to call it a bug or an issue in the repository.
  **2:42  warning  Argument 'object' should be typed with a non-any type  @typescript-eslint/explicit-module-boundary-types** 

This is the equivalent code in your repository:
https://github.com/decentralized-identity/did-jwt/blob/master/src/SignerAlgorithm.ts#L4-L7

## Steps to Reproduce
Here is what it looks like in Ubuntu on my fork [1]:
```
$ npm run lint

> did-jwt@5.12.1 lint
> eslint --ignore-pattern "src/**/*.test.[jt]s" "src/**/*.[jt]s"

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.5.4

Please only submit bug reports when using the officially supported version.

=============
jsxBracketSameLine is deprecated.

/home/ubuntu/Downloads/did-jwt/src/SignerAlg/common.ts
  2:42  warning  Argument 'object' should be typed with a non-any type  @typescript-eslint/explicit-module-boundary-types

✖ 1 problem (0 errors, 1 warning)
```
## Environment

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

[1] https://github.com/bshambaugh/did-jwt/blob/refactor/src/SignerAlg/common.ts

**Comment by mirceanis** [comment] 2022-02-23 12:37
This is not a bug, that code is intentionally phrased that way since it has to deal with `any` data type.
I'm not sure why the comment above (`// eslint-disable-next-line @typescript-eslint/no-explicit-any`) doesn't disable the warning for you.

Closing this now, please reopen if you still have questions on this topic.

**Closed by mirceanis** 2022-02-23 12:37 UTC
