### ISSUE TITLE
Verification of ed25519 signature in prod app takes 3-5x more time

### ISSUE THREAD

**Issue by ukstv** [decentralized-identity/did-jwt#190] opened 2021-07-14 11:43 UTC
### Current Behavior

Vanilla JS check script like https://gist.github.com/ukstv/5038bcb000808e2b349f8b6f7956d6b3 reports it takes about 20ms for signature verification. If run inside a full application like https://github.com/ceramicnetwork/js-ceramic (if similarly wrapped in `console.time`/`console.timeEnd`) it takes 70-100ms to do the same. I find it odd that verification time depends on the application so much.

### Expected Behavior

Time required for verification should be similar, not 3-5x larger.

#### Environment Details

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* node/browser version: v14.17.1
* OS Version: macOS Big Sur (Darwin feather 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64)
* Device details: Intel MBP

**Comment by ukstv** [comment] 2021-07-14 11:43
Maybe it is Node internals messing here, but anyway this seems odd.

**Comment by mirceanis** [comment] 2021-07-14 12:38
Thank you for reporting this.
Please provide some project that reproduces this and shows consistent difference between the two setups.
I'm tempted to think it is not a bug with this library, but rather with the setup.

**Comment by ukstv** [comment] 2021-07-14 16:29
> Please provide some project that reproduces this and shows consistent difference between the two setups

Already did:
https://gist.github.com/ukstv/5038bcb000808e2b349f8b6f7956d6b3 vs https://github.com/ceramicnetwork/js-ceramic

**Comment by mirceanis** [comment] 2021-07-14 16:47
I am unfamiliar with js-ceramic
can you point to a script based on js-ceramic that shows how this library is behaving slower than expected?

**Comment by kdenhartog** [comment] 2021-07-14 23:57
@ukstv how are you benchmarking the js-ceramic side of things?

A shot in the dark guess makes me think it's likely either latency from DID resolution (your script doesn't do any network requests to resolve the DID) or potentially a key conversion

**Comment by ukstv** [comment] 2021-07-15 05:51
@kdenhartog Simplest way to expose this:
1. git clone js-ceramic,
2. `npm install && npm run build`
3. Go to `node_modules/dids/lib/did.js`, line 132: `did_jwt_1.verifyJWS(jws, publicKeys);`
4. Wrap the line with `console.time('did-jwt.verifyJWS') ... console.timeEnd('did-jwt.verifyJWS')`
5. `cd core && npm run test`.

There you can see the time it takes for the function to complete. Note, DID resolution happens few lines above and does not affect did-jwt.verifyJWS in any way.

**Comment by kdenhartog** [comment] 2021-07-15 07:21
It's because there's more keys in the publicKeys array then in the example you wrote. Basically what's happening is the code is iterating through all possible keys in the pubKeys array (could be checking each signature - not sure didn't dig this deep) and that slows things down. It might be possible to look at the `kid` in the jwt headers to match an id in the pubKeys array to optimize the implementation a bit.

Here's an example where things run slower: https://gist.github.com/kdenhartog/075e8349af69a8e8f9891ee75543607b

**Comment by kdenhartog** [comment] 2021-07-15 07:30
Found the answer: https://github.com/decentralized-identity/did-jwt/blob/95ed4688bdaa04137930d186500e67c5e96fed4e/src/VerifierAlgorithm.ts#L131

It's doing as I suspected and iterating through all the publicKeys to verify the signature.

@mirceanis this implementation can be optimized by optionally passing the `kid` down to this function from the decodeJWS function and matching on that first before verifying. In the case where a `kid` isn't available the current implementation is a good fallback option.

**Comment by mirceanis** [comment] 2021-07-15 08:15
Thanks for the examples and for finding the "culprit" code :)

This behavior of iterating through possible verification methods and checking each one has been there from the early days, and will likely always remain (possibly only as a fallback).

Using the verification method identified by a `kid` is a planned improvement to this library.
Essentially, if there is a `kid` present in a header, then it must be used to filter through the `publicKeys` and only pick a matching key id for the actual cryptographic verification.

I'll close this issue now since the "slowness" has been identified.

**Closed by mirceanis** 2021-07-15 08:15 UTC
Labels: incomplete, triage
